### ISSUE TITLE
Sticky UITableView section header is gone

### ISSUE THREAD

**Issue by wonderffee** [ole/OLEContainerScrollView#14] opened 2015-08-11 10:42 UTC
In your demo, if a section header is added to the tableview, it will not keep sticky, how can make it work?

**Comment by ole** [comment] 2015-08-12 09:31
Actually, section headers do stick to the top, but the top of the table view is under the navigation bar in the demo app. If you hide the navigation bar, you will see that the header are sticky.

To make this work correctly, you would need to set an appropriate `contentInset` on the child table views. The problem is that then the table views are not being laid out correctly in the initial scroll position. We'll probably have to adjust `-[OLEContainerScrollView layoutSubviews]` accordingly to take content insets into account.

I can't promise when I will have time to look into this further.

**Comment by ole** [comment] 2018-09-18 16:29
Closing this because I'm going to [archive this project](https://help.github.com/articles/archiving-a-github-repository/).

**Closed by ole** 2018-09-18 16:29 UTC
