### ISSUE TITLE
Add custom UIView as subview, constraint it with auto layout not position correct in scrollview

### ISSUE THREAD

**Issue by danjiang** [ole/OLEContainerScrollView#16] opened 2016-04-25 08:40 UTC
When I add a custom UIView to OLEContainerScrollView. 
And layout this custom UIView`s subviews with auto layout. The custom UIView will not position correct in scrollview.
But manually layout custom UIView`s subviews with frame, everything will be work.

**Comment by ole** [comment] 2016-04-25 09:04
> The custom UIView will not position correct in scrollview.

What happens? How is the view positioned incorrectly?

I can’t think of anything why using autolayout in the subview should affect the layout of the container.

**Comment by danjiang** [comment] 2016-04-25 09:25
![scroll](https://cloud.githubusercontent.com/assets/696283/14779236/c5ec6fb4-0b09-11e6-859b-f3445fbb29a4.gif)

```
HVAccountProfileView *profileView = [[HVAccountProfileView alloc] initWithFrame:CGRectMake(0, 0, 0, 169)];
profileView.backgroundColor = [UIColor redColor];

HVAccountUsersView *usersView = [HVAccountUsersView new];
usersView.backgroundColor = [UIColor blueColor];

[self.contentView addSubview:profileView];
[self.contentView addSubview:usersView];
```

HVAccountProfileView  and HVAccountUsersView are both subclass of UIView.
HVAccountUsersView use intrinsicContentSize return the size information.

**Comment by danjiang** [comment] 2016-04-25 09:46
From my point. Custom view layout its subviews use auto layout. It will calculate its bounds base on those constraints. So set custom view`s frame through initWithFrame or change its frame when scroll will not position correctly.

```
else {
	// Normal views are simply positioned at the current offset
	CGRect frame = subview.frame;
	frame.origin.y = yOffsetOfCurrentSubview;
	frame.size.width = self.contentView.bounds.size.width;
	subview.frame = frame;
	
	yOffsetOfCurrentSubview += frame.size.height;
}
```

**Comment by danjiang** [comment] 2016-05-04 09:28
Just another comment. Maybe help. I layout subview with SnapKit in Swift. Everything work fine. But previous code layout subview with Masonry in Objective-C.

**Comment by ole** [comment] 2016-05-04 09:34
I didn't have time to look at this yet, but I think the problem is that `OLEContainerScrollView` does not react to changes of the `intrinsicContentSize` of its subviews. It simply expects that the subviews' size remains constant. I hope to be able to take a look at this in the next few days, but I can't promise that I will find the time.

**Comment by ole** [comment] 2016-05-11 10:48
I just pushed a fix that should make the container view behave better with subviews that use auto layout. I also added another screen to the demo app that uses subviews with auto layout.

This works more or less, but it uses a dirty hack to notify the container scroll view when one of the subviews wants to update its preferred size. Making it fully compatible with views using auto layout would require switching the entire layout logic to constraints, I think. At least I can't think of another solution.

**Comment by danjiang** [comment] 2016-05-12 01:57
@ole Thanks for taking a look at this problem. 

> Making it fully compatible with views using auto layout would require switching the entire layout logic to constraints

You means change OLEContainerScrollView`s layoutSubviews and observer base on layout logic with constraints?

**Comment by ole** [comment] 2016-05-12 12:05
Basically, yes. I think we would need to change `didAddSubviewToContainer:` and `willRemoveSubviewFromContainer:` so that these methods create appropriate constraints for the child views. We could then probably delete a bunch of code from `layoutSubviews` because the constraints would do some of the work.

We would still need special handling of child views that are subclasses of `UIScrollView`, however. And there may be other complications. I haven't thought this through completely.

**Comment by ole** [comment] 2018-09-18 16:29
Closing this because I'm going to [archive this project](https://help.github.com/articles/archiving-a-github-repository/).

**Closed by ole** 2018-09-18 16:29 UTC
